language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t yogihulk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yogihulk/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  environment: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-992253114471"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"